print("Let's do some math")
print( "add two numbers'")
num1 = input ("Enter 1st number = ")
num2 = input ("Enter 2nd number = ")
result = float(num1) + float(num2)
print("total value is = {0}".format(result) )